# See https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
# Swap the image path below to wall0.png / wall1.png if you prefer a different one.

preload = /home/shellwalker/Pictures/wallpapers/flower-branch.png

wallpaper = DP-3,/home/shellwalker/Pictures/wallpapers/flower-branch.png
wallpaper = DP-2,/home/shellwalker/Pictures/wallpapers/flower-branch.png

splash = false
ipc = on
